### ISSUE TITLE
CheatBreaker Crashing after a Reskin

### ISSUE THREAD

**Issue by ghost** [ItsVops/CB-Cosmetics-API#2]
Hello,

I'm creating this issue to ask for assistance because although I've followed the guide, and my client has connected to the API, I cannot join servers/play on worlds and the client crashes when I attempt to do so. Please help me with this.

**Comment by vopswtf** [comment]
That is probably something to do with what your using to edit the jar. What
program are you using?

**Comment by ghost** [comment]
> That is probably something to do with what your using to edit the jar. What program are you using?

I'm currently using JByteMod v1.8.2 by GraxCode.

**Comment by ghost** [comment]
I've used the JByteMod Reborn version from the GitHub repo, and it works. I should have read this repo further. Thank you for the help!
