### ISSUE TITLE
Feature Request: Banning players

### ISSUE THREAD

**Issue by ghost** [ItsVops/CB-Cosmetics-API#4]
Hello,

I have a suggestion/Feature Request: Maybe add the functionality to ban users from using the client? It could be an account ban, it doesn't have to be an IP/HWID ban, but just something to blacklist users from using the client.

**Comment by vopswtf** [comment]
This could be possible, but easily bypassed by editing the jar or turning
off your wifi for launch.

**Comment by ghost** [comment]
> This could be possible, but easily bypassed by editing the jar or turning off your wifi for launch.

I still think it might be a cool feature to mess with your friends, but you do have a point.

**Comment by vopswtf** [comment]
Resolved
